# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ozonmp/bss_workplace_facade/v1/bss_workplace_facade.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from validate import validate_pb2 as validate_dot_validate__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ozonmp/bss_workplace_facade/v1/bss_workplace_facade.proto',
  package='ozonmp.bss_workplace_api.v1',
  syntax='proto3',
  serialized_options=_b('ZTgithub.com/ozonmp/bss-workplace-facade/pkg/bss-workplace-facade;bss_workplace_facade'),
  serialized_pb=_b('\n9ozonmp/bss_workplace_facade/v1/bss_workplace_facade.proto\x12\x1bozonmp.bss_workplace_api.v1\x1a\x17validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n\tWorkplace\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n\x04size\x18\x03 \x01(\rR\x04size\x12\x34\n\x07\x63reated\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x07\x63reated\"\xa8\x01\n\x0eWorkplaceEvent\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\x1d\n\nevent_type\x18\x02 \x01(\rR\teventType\x12!\n\x0c\x65vent_status\x18\x03 \x01(\rR\x0b\x65ventStatus\x12\x44\n\tworkplace\x18\x04 \x01(\x0b\x32&.ozonmp.bss_workplace_api.v1.WorkplaceR\tworkplaceBVZTgithub.com/ozonmp/bss-workplace-facade/pkg/bss-workplace-facade;bss_workplace_facadeb\x06proto3')
  ,
  dependencies=[validate_dot_validate__pb2.DESCRIPTOR,google_dot_api_dot_annotations__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_WORKPLACE = _descriptor.Descriptor(
  name='Workplace',
  full_name='ozonmp.bss_workplace_api.v1.Workplace',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ozonmp.bss_workplace_api.v1.Workplace.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='ozonmp.bss_workplace_api.v1.Workplace.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='name', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='ozonmp.bss_workplace_api.v1.Workplace.size', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='size', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='ozonmp.bss_workplace_api.v1.Workplace.created', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='created', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=299,
)


_WORKPLACEEVENT = _descriptor.Descriptor(
  name='WorkplaceEvent',
  full_name='ozonmp.bss_workplace_api.v1.WorkplaceEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='ozonmp.bss_workplace_api.v1.WorkplaceEvent.id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='id', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='ozonmp.bss_workplace_api.v1.WorkplaceEvent.event_type', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='eventType', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='event_status', full_name='ozonmp.bss_workplace_api.v1.WorkplaceEvent.event_status', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='eventStatus', file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='workplace', full_name='ozonmp.bss_workplace_api.v1.WorkplaceEvent.workplace', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='workplace', file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=302,
  serialized_end=470,
)

_WORKPLACE.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_WORKPLACEEVENT.fields_by_name['workplace'].message_type = _WORKPLACE
DESCRIPTOR.message_types_by_name['Workplace'] = _WORKPLACE
DESCRIPTOR.message_types_by_name['WorkplaceEvent'] = _WORKPLACEEVENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Workplace = _reflection.GeneratedProtocolMessageType('Workplace', (_message.Message,), dict(
  DESCRIPTOR = _WORKPLACE,
  __module__ = 'ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.bss_workplace_api.v1.Workplace)
  ))
_sym_db.RegisterMessage(Workplace)

WorkplaceEvent = _reflection.GeneratedProtocolMessageType('WorkplaceEvent', (_message.Message,), dict(
  DESCRIPTOR = _WORKPLACEEVENT,
  __module__ = 'ozonmp.bss_workplace_facade.v1.bss_workplace_facade_pb2'
  # @@protoc_insertion_point(class_scope:ozonmp.bss_workplace_api.v1.WorkplaceEvent)
  ))
_sym_db.RegisterMessage(WorkplaceEvent)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
