// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: ozonmp/bss_workplace_facade/v1/bss_workplace_facade.proto

package bss_workplace_facade

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workplace struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Size    uint32                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Created *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created,proto3" json:"created,omitempty"`
}

func (x *Workplace) Reset() {
	*x = Workplace{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workplace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workplace) ProtoMessage() {}

func (x *Workplace) ProtoReflect() protoreflect.Message {
	mi := &file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workplace.ProtoReflect.Descriptor instead.
func (*Workplace) Descriptor() ([]byte, []int) {
	return file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDescGZIP(), []int{0}
}

func (x *Workplace) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Workplace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workplace) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Workplace) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

type WorkplaceEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64     `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	EventType   uint32     `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventStatus uint32     `protobuf:"varint,3,opt,name=event_status,json=eventStatus,proto3" json:"event_status,omitempty"`
	Workplace   *Workplace `protobuf:"bytes,4,opt,name=workplace,proto3" json:"workplace,omitempty"`
}

func (x *WorkplaceEvent) Reset() {
	*x = WorkplaceEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkplaceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkplaceEvent) ProtoMessage() {}

func (x *WorkplaceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkplaceEvent.ProtoReflect.Descriptor instead.
func (*WorkplaceEvent) Descriptor() ([]byte, []int) {
	return file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDescGZIP(), []int{1}
}

func (x *WorkplaceEvent) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkplaceEvent) GetEventType() uint32 {
	if x != nil {
		return x.EventType
	}
	return 0
}

func (x *WorkplaceEvent) GetEventStatus() uint32 {
	if x != nil {
		return x.EventStatus
	}
	return 0
}

func (x *WorkplaceEvent) GetWorkplace() *Workplace {
	if x != nil {
		return x.Workplace
	}
	return nil
}

var File_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto protoreflect.FileDescriptor

var file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDesc = []byte{
	0x0a, 0x39, 0x6f, 0x7a, 0x6f, 0x6e, 0x6d, 0x70, 0x2f, 0x62, 0x73, 0x73, 0x5f, 0x77, 0x6f, 0x72,
	0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x66, 0x61, 0x63, 0x61, 0x64, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x62, 0x73, 0x73, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x66,
	0x61, 0x63, 0x61, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x6f, 0x7a, 0x6f,
	0x6e, 0x6d, 0x70, 0x2e, 0x62, 0x73, 0x73, 0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x1a, 0x17, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e,
	0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x79, 0x0a, 0x09, 0x57, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x34, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x22, 0xa8, 0x01, 0x0a, 0x0e,
	0x57, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a,
	0x0c, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0b, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x44, 0x0a, 0x09, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x7a, 0x6f, 0x6e, 0x6d, 0x70, 0x2e, 0x62, 0x73, 0x73,
	0x5f, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x52, 0x09, 0x77, 0x6f, 0x72,
	0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x42, 0x56, 0x5a, 0x54, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x7a, 0x6f, 0x6e, 0x6d, 0x70, 0x2f, 0x62, 0x73, 0x73, 0x2d,
	0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x2d, 0x66, 0x61, 0x63, 0x61, 0x64, 0x65,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x62, 0x73, 0x73, 0x2d, 0x77, 0x6f, 0x72, 0x6b, 0x70, 0x6c, 0x61,
	0x63, 0x65, 0x2d, 0x66, 0x61, 0x63, 0x61, 0x64, 0x65, 0x3b, 0x62, 0x73, 0x73, 0x5f, 0x77, 0x6f,
	0x72, 0x6b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x66, 0x61, 0x63, 0x61, 0x64, 0x65, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDescOnce sync.Once
	file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDescData = file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDesc
)

func file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDescGZIP() []byte {
	file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDescOnce.Do(func() {
		file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDescData = protoimpl.X.CompressGZIP(file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDescData)
	})
	return file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDescData
}

var file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_goTypes = []interface{}{
	(*Workplace)(nil),             // 0: ozonmp.bss_workplace_api.v1.Workplace
	(*WorkplaceEvent)(nil),        // 1: ozonmp.bss_workplace_api.v1.WorkplaceEvent
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_depIdxs = []int32{
	2, // 0: ozonmp.bss_workplace_api.v1.Workplace.created:type_name -> google.protobuf.Timestamp
	0, // 1: ozonmp.bss_workplace_api.v1.WorkplaceEvent.workplace:type_name -> ozonmp.bss_workplace_api.v1.Workplace
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_init() }
func file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_init() {
	if File_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workplace); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkplaceEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_goTypes,
		DependencyIndexes: file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_depIdxs,
		MessageInfos:      file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_msgTypes,
	}.Build()
	File_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto = out.File
	file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_rawDesc = nil
	file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_goTypes = nil
	file_ozonmp_bss_workplace_facade_v1_bss_workplace_facade_proto_depIdxs = nil
}
